name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debug repo tree
      run: |
        pwd
        ls -la

    - name: SCANOSS Code Scan Action
      uses: scanoss/gha-code-scan@v1.7.0

    - name: Build
      run: |
        npm --ignore-scripts install
        npm ci --ignore-scripts
        npx --ignore-scripts webpack
